server:
  port: 9191

spring:
  application:
    name: backend-resources

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/ITM

keycloak:
  realm: ITM
  resource: backend-resources
  auth-server-url: http://localhost:8080/auth
  credentials:
    secret: fA5thyv4VMIx7mOkcBuqNkjPqeFDjHBP
